
[general]
	#true - saves inventory every N seconds.
	tickSaveEnabled = true
	#Determines the frequency at which inventory will be saved. 60 - every minute, -1 - never.
	#Range: -1 ~ 9223372036854775807
	preservationPeriod = 60
	#true - saves inventory on death
	deadSaveEnabled = true

